Repository botuniverse/php-libonebot, pull requests merged in 2021-11, with the labels that each got.

#8 fix missing arg in PrivateMessageEvent
  src/OneBot/V12/Object/Event/Message/PrivateMessageEvent.php
Labels: bug

#16 增加对象池
  composer.json
  src/OneBot/ObjectPool/AbstractObjectPool.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#14 实现 OneBot 扩展事件
  src/OneBot/V12/Object/Event/Message/ExtendedMessageEvent.php
  src/OneBot/V12/Object/Event/Message/MessageEvent.php
  src/OneBot/V12/Object/Event/Meta/ExtendedMetaEvent.php
  src/OneBot/V12/Object/Event/Meta/HeartbeatEvent.php
  src/OneBot/V12/Object/Event/Meta/MetaEvent.php
  src/OneBot/V12/Object/Event/Notice/ExtendedNoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupAdminSetEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupAdminUnsetEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberBanEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberUnbanEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/Notice/NoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/PrivateMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/OneBotEvent.php
  src/OneBot/V12/Object/Event/Request/ExtendedRequestEvent.php
  src/OneBot/V12/Object/Event/Request/RequestEvent.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#19 更换全局名称防止冲突
  src/OneBot/Database/SQLite/SQLite.php
  src/OneBot/V12/Action/ReplAction.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/global_defines.php
Labels: area/function, kind/suggest, lifecycle/ready-for-merge

#18 增加 Dependabot 支持
  .github/dependabot.yml
Labels: area/workflow, kind/suggest, lifecycle/ready-for-merge

#20 完善 SwooleDriver 目前开发完成的部分
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#17 支持 SQLite
  cache/.gitkeep
  composer.json
  demo.json
  src/OneBot/Database/SQLite/ConnectionPool.php
  src/OneBot/Database/SQLite/SQLite.php
  src/OneBot/V12/Action/ReplAction.php
  src/OneBot/V12/Config/Config.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/global_defines.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#21 发布 0.3.0
  .github/dependabot.yml
  .github/label-actions.yaml
  .github/workflows/close-staled.yaml
  .github/workflows/integration-test.yaml
  .github/workflows/label-actions.yaml
  .php-cs-fixer.php
  README.md
  cache/.gitkeep
  composer.json
  demo.json
  demo.php
  docs/update.md
  phpstan.neon
  src/OneBot/Database/SQLite/ConnectionPool.php
  src/OneBot/Database/SQLite/SQLite.php
  src/OneBot/ObjectPool/AbstractObjectPool.php
  src/OneBot/V12/Action/ActionBase.php
  src/OneBot/V12/Action/ReplAction.php
  src/OneBot/V12/Config/Config.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/Workerman/Worker.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/Object/Event/HasGroupId.php
  src/OneBot/V12/Object/Event/HasMessageId.php
  src/OneBot/V12/Object/Event/HasOperatorId.php
  src/OneBot/V12/Object/Event/HasUserId.php
  src/OneBot/V12/Object/Event/Message/ExtendedMessageEvent.php
  src/OneBot/V12/Object/Event/Message/GroupMessageEvent.php
  src/OneBot/V12/Object/Event/Message/MessageEvent.php
  src/OneBot/V12/Object/Event/Message/PrivateMessageEvent.php
  src/OneBot/V12/Object/Event/Meta/ExtendedMetaEvent.php
  src/OneBot/V12/Object/Event/Meta/HeartbeatEvent.php
  src/OneBot/V12/Object/Event/Meta/MetaEvent.php
  src/OneBot/V12/Object/Event/Notice/ExtendedNoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupAdminSetEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupAdminUnsetEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberBanEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMemberUnbanEvent.php
  src/OneBot/V12/Object/Event/Notice/GroupMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/Notice/NoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/PrivateMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/OneBotEvent.php
  src/OneBot/V12/Object/Event/Request/ExtendedRequestEvent.php
  src/OneBot/V12/Object/Event/Request/RequestEvent.php
  src/OneBot/V12/Object/EventObject.php
  src/OneBot/V12/Object/MessageSegment.php
  src/OneBot/V12/OneBot.php
  src/OneBot/V12/global_defines.php
Labels: area/function, blocked/require-more-info, status/wait-for-review
