Repository botuniverse/php-libonebot, pull requests merged in 2022-01, with the labels that each got.

#27 不同 Driver 多进程相关 API
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/Workerman/Worker.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/MPUtils.php
  src/OneBot/V12/Utils.php
  src/OneBot/V12/global_defines.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#22 增加 HTTP psr 合规
  .php-cs-fixer.php
  composer.json
  src/OneBot/Http/HttpFactory.php
  src/OneBot/Http/MessageTrait.php
  src/OneBot/Http/Request.php
  src/OneBot/Http/RequestTrait.php
  src/OneBot/Http/Response.php
  src/OneBot/Http/ServerRequest.php
  src/OneBot/Http/Stream.php
  src/OneBot/Http/Uri.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/Swoole/HttpClient.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/global_defines.php
Labels: area/function, kind/feature, status/wait-for-review

#30 优化和调整部分类的命名空间
  src/OneBot/Util/MPUtils.php
  src/OneBot/Util/Utils.php
  src/OneBot/V12/Action/ActionBase.php
  src/OneBot/V12/Action/ExtendedActionInterface.php
  src/OneBot/V12/Action/ReplAction.php
  src/OneBot/V12/ActionHandler.php
  src/OneBot/V12/Config/Config.php
  src/OneBot/V12/Console.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#28 PSR-18 HTTP 客户端实现 / WebSocket 客户端实现
  composer.json
  src/OneBot/Http/Client/CurlClient.php
  src/OneBot/Http/Client/Exception/ClientException.php
  src/OneBot/Http/Client/Exception/NetworkException.php
  src/OneBot/Http/Client/Exception/RequestException.php
  src/OneBot/Http/Client/StreamClient.php
  src/OneBot/Http/Client/SwooleClient.php
  src/OneBot/Http/Client/WorkermanClient.php
  src/OneBot/Http/HttpFactory.php
  src/OneBot/Http/MessageTrait.php
  src/OneBot/Http/Response.php
  src/OneBot/Util/MPUtils.php
  src/OneBot/Util/Utils.php
  src/OneBot/V12/Action/ActionBase.php
  src/OneBot/V12/Action/ExtendedActionInterface.php
  src/OneBot/V12/Action/ReplAction.php
  src/OneBot/V12/ActionHandler.php
  src/OneBot/V12/Config/Config.php
  src/OneBot/V12/Console.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/Swoole/WebSocketClient.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WebSocketClientInterface.php
  src/OneBot/V12/Driver/Workerman/WebSocketClient.php
  src/OneBot/V12/Driver/Workerman/Worker.php
  src/OneBot/V12/Driver/WorkermanDriver.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#33 添加 PHPUnit 的支持，方便对测试脚本做一个规范化留存
  .gitignore
  composer.json
  test/feature/fluent-console-color/ConsoleColorTest.php
Labels: area/workflow, kind/feature, lifecycle/ready-for-merge

#32 重构控制台颜色类
  .gitignore
  composer.json
  src/OneBot/Logger/Console/ConsoleColor.php
  src/OneBot/Logger/Console/ConsoleLogger.php
  src/OneBot/Logger/Console/TermColor.php
  src/OneBot/Util/Utils.php
  src/OneBot/V12/global_defines.php
  test/feature/fluent-console-color/ConsoleColorTest.php
Labels: area/function, kind/feature, status/wip

#34 新增事件分发器和调整 Driver 更加独立
  src/OneBot/Driver/Driver.php
  src/OneBot/Driver/Event/DriverEvent.php
  src/OneBot/Driver/Event/Event.php
  src/OneBot/Driver/Event/EventDispatcher.php
  src/OneBot/Driver/Event/EventProvider.php
  src/OneBot/Driver/Event/HttpRequestEvent.php
  src/OneBot/Driver/Event/StopException.php
  src/OneBot/Driver/Event/WebSocketCloseEvent.php
  src/OneBot/Driver/Event/WebSocketMessageEvent.php
  src/OneBot/Driver/Event/WebSocketOpenEvent.php
  src/OneBot/Driver/Event/WorkerStartEvent.php
  src/OneBot/Driver/Event/WorkerStopEvent.php
  src/OneBot/Driver/Swoole/WebSocketClient.php
  src/OneBot/Driver/SwooleDriver.php
  src/OneBot/Driver/WebSocketClientInterface.php
  src/OneBot/Driver/Workerman/WebSocketClient.php
  src/OneBot/Driver/Workerman/Worker.php
  src/OneBot/Driver/WorkermanDriver.php
  src/OneBot/Http/HttpFactory.php
  src/OneBot/Logger/Console/ConsoleLogger.php
  src/OneBot/Util/MPUtils.php
  src/OneBot/Util/Utils.php
  src/OneBot/V12/Driver/Driver.php
  src/OneBot/V12/Driver/SwooleDriver.php
  src/OneBot/V12/Driver/WorkermanDriver.php
  src/OneBot/V12/OneBot.php
  src/OneBot/V12/OneBotEventListener.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#35 修复 Review 标签自动化冲突
  .github/workflows/review-actions.yaml
Labels: area/workflow, lifecycle/ready-for-merge

#36 引入 Collision 包进行异常处理美化
  composer.json
  src/OneBot/Driver/SwooleDriver.php
  src/OneBot/Driver/WorkermanDriver.php
  src/OneBot/Logger/Console/ConsoleLogger.php
  src/OneBot/Logger/Console/ExceptionHandler.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge
