Repository botuniverse/php-libonebot, pull requests merged in 2022-09, with the labels that each got.

#66 重构 Driver Socket 传递配置文件的方式
  src/OneBot/Driver/Event/DriverEvent.php
  src/OneBot/Driver/Interfaces/SocketInterface.php
  src/OneBot/Driver/Socket/HttpClientSocketBase.php
  src/OneBot/Driver/Socket/HttpServerSocketBase.php
  src/OneBot/Driver/Socket/SocketConfig.php
  src/OneBot/Driver/Socket/WSClientSocketBase.php
  src/OneBot/Driver/Socket/WSServerSocketBase.php
  src/OneBot/Driver/Swoole/Socket/HttpServerSocket.php
  src/OneBot/Driver/Swoole/Socket/WSServerSocket.php
  src/OneBot/Driver/Swoole/SwooleDriver.php
  src/OneBot/Driver/Swoole/TopEventListener.php
  src/OneBot/Driver/Workerman/Socket/HttpServerSocket.php
  src/OneBot/Driver/Workerman/TopEventListener.php
  src/OneBot/Driver/Workerman/WorkermanDriver.php
  src/OneBot/V12/OneBotEventListener.php
  tests/OneBot/V12/OneBotEventListenerTest.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#67 重构 Workflow
  .github/workflows/coding-style-analysis.yml
  .github/workflows/coding-style.yml
  .github/workflows/integration-test.yaml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: area/workflow, kind/feature, lifecycle/ready-for-merge

#69 [WIP] 重构配置模块
  .php-cs-fixer.php
  README.md
  src/OneBot/Config/Config.php
  src/OneBot/Config/Loader/AbstractFileLoader.php
  src/OneBot/Config/Loader/DelegateLoader.php
  src/OneBot/Config/Loader/JsonFileLoader.php
  src/OneBot/Config/Loader/LoadException.php
  src/OneBot/Config/Loader/LoaderInterface.php
  src/OneBot/Config/Repository.php
  src/OneBot/Config/RepositoryInterface.php
  src/OneBot/Driver/Driver.php
  src/OneBot/V12/OneBot.php
  src/OneBot/V12/OneBotBuilder.php
  tests/OneBot/Config/ConfigTest.php
  tests/OneBot/Config/RepositoryTest.php
  tests/OneBot/GlobalDefinesTest.php
  tests/OneBot/V12/Action/ActionBaseTest.php
  tests/OneBot/V12/Action/ActionResponseTest.php
  tests/OneBot/V12/OneBotEventListenerTest.php
  tests/OneBot/V12/RetCodeTest.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#70 修复配置加载器在 Windows 下的绝对路径问题
  src/OneBot/Config/Loader/AbstractFileLoader.php
  tests/Fixture/config.json
  tests/Fixture/invalid.json
  tests/OneBot/Config/ConfigTest.php
  tests/OneBot/Config/Loader/AbstractFileLoaderTest.php
  tests/OneBot/Config/Loader/DelegateLoaderTest.php
  tests/OneBot/Config/Loader/JsonFileLoaderTest.php
Labels: area/function, kind/bug, lifecycle/ready-for-merge
