Repository botuniverse/php-libonebot, pull requests merged in 2022-12, with the labels that each got.

#76 重构 OneBotEvent，删除一堆对象，编写 Validator
  demo/repl.php
  demo/weixin.php
  src/OneBot/V12/EventBuilder.php
  src/OneBot/V12/Object/Event/HasChannelId.php
  src/OneBot/V12/Object/Event/HasGroupId.php
  src/OneBot/V12/Object/Event/HasGuildId.php
  src/OneBot/V12/Object/Event/HasMessageId.php
  src/OneBot/V12/Object/Event/HasOperatorId.php
  src/OneBot/V12/Object/Event/HasUserId.php
  src/OneBot/V12/Object/Event/Message/ChannelMessageEvent.php
  src/OneBot/V12/Object/Event/Message/ExtendedMessageEvent.php
  src/OneBot/V12/Object/Event/Message/GroupMessageEvent.php
  src/OneBot/V12/Object/Event/Message/MessageEvent.php
  src/OneBot/V12/Object/Event/Message/PrivateMessageEvent.php
  src/OneBot/V12/Object/Event/Meta/ExtendedMetaEvent.php
  src/OneBot/V12/Object/Event/Meta/HeartbeatEvent.php
  src/OneBot/V12/Object/Event/Meta/MetaEvent.php
  src/OneBot/V12/Object/Event/Meta/StatusUpdateEvent.php
  src/OneBot/V12/Object/Event/Notice/ExtendedNoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/FriendIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/Group/GroupMemberDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/Group/GroupMemberIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/Group/GroupMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/Notice/Group/GroupNoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/ChannelCreateEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/ChannelDeleteEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/ChannelMemberDecreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/ChannelMemberIncreaseEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/ChannelMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/Notice/Guild/GuildNoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/NoticeEvent.php
  src/OneBot/V12/Object/Event/Notice/PrivateMessageDeleteEvent.php
  src/OneBot/V12/Object/Event/OneBotEvent.php
  src/OneBot/V12/Object/Event/Request/ExtendedRequestEvent.php
  src/OneBot/V12/Object/Event/Request/RequestEvent.php
  src/OneBot/V12/Object/OneBotEvent.php
  src/OneBot/V12/OneBot.php
  src/OneBot/V12/Validator.php
  src/OneBot/global_defines.php
  tests/OneBot/V12/Object/Event/Message/ChannelMessageEventTest.php
  tests/OneBot/V12/Object/Event/Message/GroupMessageEventTest.php
  tests/OneBot/V12/Object/Event/Message/PrivateMessageEventTest.php
Labels: area/function, kind/suggest, lifecycle/ready-for-merge

#77 根据最新的 OneBot 12 标准文档更正 Action 对象
  src/OneBot/V12/Object/Action.php
  src/OneBot/V12/Object/OneBotEvent.php
  src/OneBot/global_defines.php
Labels: area/function, lifecycle/ready-for-merge

#78 修复一个 Response 的 Bug，新增 OneBotEvent 对象的方法
  src/OneBot/Driver/Event/WebSocket/WebSocketOpenEvent.php
  src/OneBot/V12/Object/OneBotEvent.php
Labels: area/function, kind/bug, lifecycle/ready-for-merge

#79 0.5.0 release (remove choir temporarily)
  composer.json
  src/OneBot/Driver/Choir/ChoirDriver.php
  src/OneBot/Driver/Choir/EventLoopWrapper.php
  src/OneBot/Driver/Choir/WebSocketClient.php
  src/OneBot/global_defines.php
Labels: area/function, kind/suggest, lifecycle/ready-for-merge

#81 灵活化异常处理
  src/OneBot/Exception/ExceptionHandler.php
Labels: lifecycle/ready-for-merge

#82 协程支持（并发布 0.5.1）
  src/OneBot/Driver/Coroutine/Adaptive.php
  src/OneBot/Driver/Coroutine/CoroutineInterface.php
  src/OneBot/Driver/Coroutine/FiberCoroutine.php
  src/OneBot/Driver/Coroutine/SwooleCoroutine.php
  src/OneBot/Driver/Event/EventDispatcher.php
  src/OneBot/Driver/Swoole/TopEventListener.php
  src/OneBot/Driver/Workerman/TopEventListener.php
  src/OneBot/Exception/ExceptionHandler.php
  src/OneBot/V12/Action/ActionHandlerBase.php
  src/OneBot/global_defines.php
Labels: lifecycle/ready-for-merge

#83 移除自动发布
  .github/workflows/release.yaml
Labels: area/workflow, lifecycle/ready-for-merge

#84 修复非协程环境下无法分发事件的 Bug
  composer.json
  src/OneBot/Driver/Event/EventDispatcher.php
  src/OneBot/global_defines.php
Labels: kind/bug, lifecycle/ready-for-merge
