Repository botuniverse/php-libonebot, pull requests merged in 2023-01, with the labels that each got.

#85 移除 Fiber 无用调试信息
  src/OneBot/Driver/Coroutine/FiberCoroutine.php
Labels: kind/bug, lifecycle/ready-for-merge

#87 修复 OneBotEvent 消息缓存问题
  src/OneBot/V12/Object/OneBotEvent.php
  tests/OneBot/V12/Object/OneBotEventTest.php
Labels: area/function, kind/bug, lifecycle/ready-for-merge

#88 update to 0.5.5, support swow and add client open event for future use
  src/OneBot/Driver/Event/WebSocket/WebSocketClientOpenEvent.php
  src/OneBot/Driver/Workerman/Worker.php
  src/OneBot/global_defines.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge

#89 update to 0.5.6, support taskworker process
  src/OneBot/Driver/Swoole/TopEventListener.php
  src/OneBot/global_defines.php
Labels: area/function, kind/feature, lifecycle/ready-for-merge
